import Config

# Storage backend (set at compile time; see lib/concilio/repo.ex).
db_choice = System.get_env("CONCILIO_DB", "sqlite")

# Configure your database
case db_choice do
  "postgres" ->
    config :concilio, Concilio.Repo,
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "concilio_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10

  _ ->
    # SQLite is single-writer; pool_size > 1 only invites
    # `Database busy` errors. The Sandbox handles isolation via
    # transaction rollback in test, and dev rarely needs concurrency.
    config :concilio, Concilio.Repo,
      database: Path.expand("../priv/repo/concilio_dev.db", __DIR__),
      journal_mode: :wal,
      cache_size: -64_000,
      busy_timeout: 30_000,
      pool_size: 1,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :concilio, ConcilioWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "GFUdJbW+arlP7P8P9VJqo5rnmracVNJySX+TVTxcSNH0TVJE8urH7/WUR1mYlkFl",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:concilio, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:concilio, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :concilio, ConcilioWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/concilio_web/router\.ex$",
      ~r"lib/concilio_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :concilio, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
